# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

# localhost_development:
#   backend:
#     name: file-system
#     api_root: /api

local_backend: true

backend:
  name: github
  repo: timfitzzz/tlf
  branch: main

display_url: http://localhost:41052/
media_folder: static/assets
public_folder: assets

collections:
  - name: mdx
    label: Sections
    description: Main Sections
    folder: content/mdx
    extension: "mdx"
    format: frontmatter
    widget: mdx
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: path, name: path, widget: string, required: false }
      - { label: Body, name: body, widget: mdx }

  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: blog-post,
        }
      - { label: Title, name: title, widget: string }

      - { label: Body, name: body, widget: markdown }
